# Ansible role requirements for a Solr deployment

- src: git+https://github.com/UCLALibrary/uclalib_role_rhel8repos.git
  
- src: git+https://github.com/UCLALibrary/uclalib_role_epel.git

- src: git+https://github.com/UCLALibrary/uclalib_role_uclalibrepo.git

- src: git+https://github.com/UCLALibrary/uclalib_role_java.git

- src: git+https://github.com/UCLALibrary/uclalib_role_apache.git

