---

- name: Determine if solr is installed
  stat:
    path: "{{ solr_base_dir }}"
  register: solr_path
  changed_when: False

- name: Download Solr
  get_url:
    url: "{{ solr_url }}"
    dest: "/{{ solr_install_dir }}/solr-{{ solr_version }}.tgz"
  when: solr_path.stat.exists == False
  register: solr_download_status

- name: Install and Configure Solr
  block:
    - include_tasks: install.yml
      tags:
        - install-solr

    - include_tasks: config_env.yml
      tags: 
        - config-solr

    - include_tasks: vhost_config.yml
      tags:
        - config-vhost
  when: solr_download_status.changed

- name: Set-up Solr Cores
  include_tasks: cores.yml
  when: solr_cores is defined
  tags:
    - setup-cores

- name: Enable rsync replication
  include_tasks: rsync.yml
  when: solr_replication_node == "rsync"
  tags:
    - setup-rsync-replication
